version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: /sdks/axg-python-sdk
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /sdks/axg-node-sdk
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: nuget
    directory: /integrations/agt-dotnet
    schedule:
      interval: weekly
